import type { AutocliSpec } from "./types.js";

/**
 * Emits `convex/autocli.ts` for the target project: a read-only, internal-only
 * query surface the CLI calls via `npx convex run autocli:*`.
 *
 * Safety properties, enforced server-side (not in the CLI):
 *  - internalQuery only: unreachable from any client, read-only by construction
 *  - table allowlist baked in at generation time
 *  - secret/PII fields stripped before anything leaves the deployment
 *  - every list/count path goes through an index; no full scans
 *  - hard row caps regardless of what the caller asks for
 */
export function generateConvexModule(spec: AutocliSpec): string {
  const tables = Object.values(spec.tables);
  const tableNames = tables.map((t) => t.name);

  const redacted: Record<string, string[]> = {};
  const listFields: Record<string, string[]> = {};
  const labelFields: Record<string, string> = {};
  const belongsTo: Record<string, { field: string; table: string }[]> = {};
  const relations: Record<string, { table: string; field: string; index: string }[]> = {};
  const search: Record<string, { index: string; field: string; filterFields: string[] }[]> = {};

  for (const t of tables) {
    if (t.redactedFields.length > 0) redacted[t.name] = t.redactedFields;
    listFields[t.name] = t.identityFields;
    if (t.labelField) labelFields[t.name] = t.labelField;
    if (t.belongsTo.length > 0) belongsTo[t.name] = t.belongsTo;
    if (t.hasMany.length > 0) {
      relations[t.name] = t.hasMany.map((r) => ({ table: r.table, field: r.field, index: r.index }));
    }
    if (t.search.length > 0) {
      search[t.name] = t.search.map((s) => ({
        index: s.index,
        field: s.searchField,
        filterFields: s.filterFields,
      }));
    }
  }

  const j = (v: unknown) => JSON.stringify(v, null, 2);

  return `/* GENERATED BY autocli v0.1.0 — do not edit by hand; run \`autocli regen\`.
 *
 * Read-only admin query surface for the autocli CLI. Every function here is an
 * internalQuery: not reachable from clients, cannot write, and only callable
 * with deployment credentials via \`npx convex run\`.
 */
import { internalQueryGeneric } from "convex/server";
import type { GenericDocument } from "convex/server";
import { v } from "convex/values";
import type { Value } from "convex/values";

const TABLES: readonly string[] = ${j(tableNames)};

const REDACTED: Record<string, readonly string[]> = ${j(redacted)};

const LIST_FIELDS: Record<string, readonly string[]> = ${j(listFields)};

const LABEL_FIELDS: Record<string, string> = ${j(labelFields)};

const BELONGS_TO: Record<string, readonly { field: string; table: string }[]> = ${j(belongsTo)};

const RELATIONS: Record<string, readonly { table: string; field: string; index: string }[]> = ${j(relations)};

const SEARCH: Record<string, readonly { index: string; field: string; filterFields: readonly string[] }[]> = ${j(search)};

const MAX_LIMIT = ${spec.defaults.maxRowLimit};
const COUNT_CAP = ${spec.defaults.countCap};
const RELATED_CAP = 100;
const SCHEMA_HASH = ${JSON.stringify(spec.schemaHash)};

function assertTable(table: string): void {
  if (!TABLES.includes(table)) {
    throw new Error(\`autocli: table "\${table}" is not in the generated allowlist. Run autocli regen after schema changes.\`);
  }
}

function redact(table: string, doc: GenericDocument): GenericDocument {
  const fields = REDACTED[table];
  if (!fields || fields.length === 0) return doc;
  const out: GenericDocument = { ...doc };
  for (const f of fields) {
    if (f in out) out[f] = "[redacted]";
  }
  return out;
}

function project(table: string, doc: GenericDocument, fields?: readonly string[]): GenericDocument {
  const wanted = fields ?? LIST_FIELDS[table] ?? [];
  const out: GenericDocument = {};
  for (const f of wanted) {
    const redactedFields = REDACTED[table];
    if (redactedFields && redactedFields.includes(f)) {
      out[f] = "[redacted]";
      continue;
    }
    if (doc[f] !== undefined) out[f] = doc[f];
  }
  const creation = doc._creationTime;
  if (creation !== undefined) out._creationTime = creation;
  const id = doc._id;
  if (id !== undefined) out._id = id;
  return out;
}

const listArgs = {
  table: v.string(),
  index: v.optional(v.string()),
  eqFields: v.optional(v.array(v.string())),
  eqValues: v.optional(v.array(v.any())),
  since: v.optional(v.number()),
  until: v.optional(v.number()),
  rangeField: v.optional(v.string()),
  order: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
  limit: v.optional(v.number()),
  cursor: v.optional(v.string()),
  fields: v.optional(v.array(v.string())),
  full: v.optional(v.boolean()),
};

interface ListArgsShape {
  table: string;
  index?: string;
  eqFields?: string[];
  eqValues?: Value[];
  since?: number;
  until?: number;
  rangeField?: string;
  order?: "asc" | "desc";
  limit?: number;
  cursor?: string;
  fields?: string[];
  full?: boolean;
}

// The generic query/index builder types in convex/server are parameterized by a
// concrete DataModel; with runtime-dynamic table and index names we use the
// narrow structural surface below instead. Every call goes through withIndex /
// withSearchIndex, so index-backed access is still guaranteed.
interface RangeBuilder {
  eq(field: string, value: Value): RangeBuilder;
  gte(field: string, value: Value): RangeBuilder;
  lt(field: string, value: Value): RangeBuilder;
}
interface SearchFilterBuilder {
  search(field: string, query: string): SearchFilterBuilder;
  eq(field: string, value: Value): SearchFilterBuilder;
}
interface OrderedQuery {
  paginate(opts: { numItems: number; cursor: string | null }): Promise<{
    page: GenericDocument[];
    isDone: boolean;
    continueCursor: string;
  }>;
  take(n: number): Promise<GenericDocument[]>;
}
interface IndexedQuery extends OrderedQuery {
  order(order: "asc" | "desc"): OrderedQuery;
}
interface QueryInit {
  withIndex(index: string, range?: (q: RangeBuilder) => RangeBuilder): IndexedQuery;
  withSearchIndex(index: string, filter: (q: SearchFilterBuilder) => SearchFilterBuilder): OrderedQuery;
}
interface Db {
  query(table: string): QueryInit;
  get(id: string): Promise<GenericDocument | null>;
  normalizeId(table: string, id: string): string | null;
}
interface Ctx {
  db: Db;
}

function asCtx(ctx: { db: unknown }): Ctx {
  return ctx as unknown as Ctx;
}

function buildIndexedQuery(ctx: Ctx, a: ListArgsShape): IndexedQuery {
  assertTable(a.table);
  const eqFields = a.eqFields ?? [];
  const eqValues = a.eqValues ?? [];
  if (eqFields.length !== eqValues.length) {
    throw new Error("autocli: eqFields and eqValues must have the same length");
  }
  const index = a.index ?? "by_creation_time";
  return ctx.db.query(a.table).withIndex(index, (q) => {
    let b = q;
    for (let i = 0; i < eqFields.length; i++) {
      const f = eqFields[i];
      if (f !== undefined) b = b.eq(f, eqValues[i] ?? null);
    }
    // Convex requires bounds on the NEXT index field after the eq chain; the
    // CLI's planner passes which field that is (implicit trailing
    // _creationTime, or a declared time field like createdAt).
    const rangeField = a.rangeField ?? "_creationTime";
    // Half-open [since, until): windowed counts compose without boundary
    // double-counting.
    if (a.since !== undefined) b = b.gte(rangeField, a.since);
    if (a.until !== undefined) b = b.lt(rangeField, a.until);
    return b;
  });
}

export const list = internalQueryGeneric({
  args: listArgs,
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as ListArgsShape;
    const limit = Math.max(1, Math.min(a.limit ?? 20, MAX_LIMIT));
    const q = buildIndexedQuery(ctx, a).order(a.order ?? "desc");
    const res = await q.paginate({ numItems: limit, cursor: a.cursor ?? null });
    const page = res.page.map((doc) =>
      a.full === true ? redact(a.table, doc) : project(a.table, doc, a.fields),
    );
    return { page, isDone: res.isDone, cursor: res.isDone ? null : res.continueCursor, schemaHash: SCHEMA_HASH };
  },
});

export const get = internalQueryGeneric({
  args: { table: v.string(), id: v.string() },
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as { table: string; id: string };
    assertTable(a.table);
    const nid = ctx.db.normalizeId(a.table, a.id);
    if (nid === null) {
      return { doc: null, error: \`"\${a.id}" is not a valid id for table "\${a.table}"\` };
    }
    const doc = await ctx.db.get(nid);
    if (doc === null) return { doc: null, error: null };

    // Resolve labels for the ids this doc points at.
    const labels: Record<string, string | null> = {};
    for (const ref of BELONGS_TO[a.table] ?? []) {
      const rawId = doc[ref.field];
      if (typeof rawId !== "string") continue;
      const refDoc = await ctx.db.get(rawId);
      const labelField = LABEL_FIELDS[ref.table];
      const label = refDoc && labelField !== undefined ? refDoc[labelField] : null;
      labels[ref.field] = typeof label === "string" ? label : null;
    }

    // Bounded counts of rows in other tables pointing at this doc.
    const related: { table: string; field: string; count: number; capped: boolean }[] = [];
    for (const rel of RELATIONS[a.table] ?? []) {
      const rows = await ctx.db
        .query(rel.table)
        .withIndex(rel.index, (q) => q.eq(rel.field, nid))
        .take(RELATED_CAP + 1);
      related.push({
        table: rel.table,
        field: rel.field,
        count: Math.min(rows.length, RELATED_CAP),
        capped: rows.length > RELATED_CAP,
      });
    }

    return { doc: redact(a.table, doc), labels, related, error: null, schemaHash: SCHEMA_HASH };
  },
});

export const count = internalQueryGeneric({
  args: listArgs,
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as ListArgsShape;
    const rows = await buildIndexedQuery(ctx, a).take(COUNT_CAP + 1);
    return { count: Math.min(rows.length, COUNT_CAP), capped: rows.length > COUNT_CAP };
  },
});

export const countBy = internalQueryGeneric({
  args: { ...listArgs, by: v.string() },
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as ListArgsShape & { by: string };
    const redactedFields = REDACTED[a.table];
    if (redactedFields && redactedFields.includes(a.by)) {
      throw new Error(\`autocli: cannot group by redacted field "\${a.by}"\`);
    }
    const rows = await buildIndexedQuery(ctx, a).take(COUNT_CAP + 1);
    const capped = rows.length > COUNT_CAP;
    const counted = capped ? rows.slice(0, COUNT_CAP) : rows;
    const counts: Record<string, number> = {};
    for (const row of counted) {
      const key = row[a.by] === undefined ? "(unset)" : String(row[a.by]);
      counts[key] = (counts[key] ?? 0) + 1;
    }
    return { counts, scanned: counted.length, capped };
  },
});

// One bounded page of an exact count. The CLI drives the cursor loop, so no
// single query ever exceeds one page — exact aggregation without temp code.
export const countPage = internalQueryGeneric({
  args: { ...listArgs, by: v.optional(v.string()) },
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as ListArgsShape & { by?: string };
    const by = a.by;
    if (by !== undefined) {
      const redactedFields = REDACTED[a.table];
      if (redactedFields && redactedFields.includes(by)) {
        throw new Error(\`autocli: cannot group by redacted field "\${by}"\`);
      }
    }
    const res = await buildIndexedQuery(ctx, a)
      .order("desc")
      .paginate({ numItems: COUNT_CAP, cursor: a.cursor ?? null });
    const counts: Record<string, number> = {};
    if (by !== undefined) {
      for (const row of res.page) {
        const key = row[by] === undefined ? "(unset)" : String(row[by]);
        counts[key] = (counts[key] ?? 0) + 1;
      }
    }
    return {
      pageCount: res.page.length,
      counts,
      isDone: res.isDone,
      cursor: res.isDone ? null : res.continueCursor,
      schemaHash: SCHEMA_HASH,
    };
  },
});

export const search = internalQueryGeneric({
  args: {
    table: v.string(),
    query: v.string(),
    filterFields: v.optional(v.array(v.string())),
    filterValues: v.optional(v.array(v.any())),
    limit: v.optional(v.number()),
  },
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as {
      table: string;
      query: string;
      filterFields?: string[];
      filterValues?: Value[];
      limit?: number;
    };
    assertTable(a.table);
    const indexes = SEARCH[a.table];
    const idx = indexes?.[0];
    if (!idx) throw new Error(\`autocli: table "\${a.table}" has no search index\`);
    const filterFields = a.filterFields ?? [];
    const filterValues = a.filterValues ?? [];
    for (const f of filterFields) {
      if (!idx.filterFields.includes(f)) {
        throw new Error(
          \`autocli: "\${f}" is not a filter field of search index "\${idx.index}" (valid: \${idx.filterFields.join(", ") || "none"})\`,
        );
      }
    }
    const limit = Math.max(1, Math.min(a.limit ?? 20, MAX_LIMIT));
    const rows = await ctx.db
      .query(a.table)
      .withSearchIndex(idx.index, (q) => {
        let b = q.search(idx.field, a.query);
        for (let i = 0; i < filterFields.length; i++) {
          const f = filterFields[i];
          if (f !== undefined) b = b.eq(f, filterValues[i] ?? null);
        }
        return b;
      })
      .take(limit);
    return { results: rows.map((r) => project(a.table, r)), schemaHash: SCHEMA_HASH };
  },
});

export const whois = internalQueryGeneric({
  args: { id: v.string() },
  handler: async (rawCtx, rawArgs) => {
    const ctx = asCtx(rawCtx);
    const a = rawArgs as { id: string };
    for (const table of TABLES) {
      const nid = ctx.db.normalizeId(table, a.id);
      if (nid !== null) {
        const doc = await ctx.db.get(nid);
        return { table, doc: doc ? redact(table, doc) : null };
      }
    }
    return { table: null, doc: null };
  },
});
`;
}
